# Generated by Django 4.2.6 on 2023-11-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=30)),
                ('descripcion', models.TextField(verbose_name='')),
                ('memoria', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Iphone',
        ),
    ]
