# Generated by Django 4.2.6 on 2023-11-18 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iphone', '0002_mac_delete_iphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac',
            name='descripcion',
            field=models.CharField(max_length=250),
        ),
    ]
